export const brazueraoSpreadSheetOpenApiSchema = {
  type: 'object',
  properties: {
    range: { type: 'string', example: "'Table'!B1:G21" },
    majorDimension: { type: 'string', example: 'ROWS' },
    values: {
      type: 'array',
      items: { type: 'string' },
      example: ['Cell One', 'Cell Two'],
    },
  },
  required: ['range'],
}

export const teamOpenApiSchema = {
  type: 'object',
  properties: {
    position: { type: 'integer', example: 1 },
    team: { type: 'string', example: 'Team A' },
    acronym: { type: 'string', example: 'TA' },
    shield: { type: 'string', example: 'url_to_shield' },
    popularName: { type: 'string', example: 'Team A' },
    points: { type: 'integer', example: 30 },
    played: { type: 'integer', example: 10 },
    wins: { type: 'integer', example: 9 },
    draws: { type: 'integer', example: 1 },
    losses: { type: 'integer', example: 0 },
    goalsFor: { type: 'integer', example: 25 },
    goalsAgainst: { type: 'integer', example: 5 },
    goalDifference: { type: 'integer', example: 20 },
    winPercentage: { type: 'number', format: 'float', example: 90 },
    recentResults: {
      type: 'array',
      items: { type: 'string' },
      example: ['W', 'W', 'W', 'W', 'W'],
    },
    positionChange: { type: 'integer', example: 0 },
  },
  required: [
    'position',
    'team',
    'acronym',
    'shield',
    'popularName',
    'points',
    'played',
    'wins',
    'draws',
    'losses',
    'goalsFor',
    'goalsAgainst',
    'goalDifference',
    'winPercentage',
    'recentResults',
    'positionChange',
  ],
}
